### ISSUE TITLE
Allow replacing entire components

### ISSUE THREAD

**Issue by forman** [bcdev/chartlets#38]
Allow replacing an entire component from an output, if a component output's `property` value is empty.

**Comment by b-yogesh** [comment]
@forman , what is the reason behind this issue? What problem are we solving here?

**Comment by forman** [comment]
I have the following use case which should be typical:

If have a button supposed to start processing data. It has id "update". Once users click it, processing starts and I want to replace the button by a circular progress (of the same size) using the same id "update". As you can see, no properties involved.
